[package]
name = "dices"
version = "0.1.0"
edition = "2018"

[dependencies]
nanoid = "0.4.0"
redis = { version = "*", features = ["tokio-comp"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
warp = "0.3"